---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: directory
  path: content
  label: 'yes'
  create: all
  match: "**/*"
  new_doc_ext: md
  templates:
  - dua-lipa
- type: directory
  path: ''
  label: 'yes'
  create: all
  match: "**/*"
  templates:
  - dua-lipa
- type: directory
  path: 'yes'
  label: 'Yes'
  create: all
  match: "**/*"
  templates:
  - dua-lipa
upload_dir: uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":year:/:month:/:day:/:filename:"
build:
  preview_env:
  - JEKYLL_ENV=staging
  preview_output_directory: _site
  install_dependencies_command: bundle install --path vendor/bundle
  preview_docker_image: forestryio/build:latest
  mount_path: "/opt/buildhome/repo"
  instant_preview_command: bundle exec jekyll serve --drafts --unpublished --future
    --port 8080 --host 0.0.0.0 -d _site
